apiVersion: apps/v1
kind: Deployment
metadata:
  name: ancients-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ancients
  template:
    metadata:
      labels:
        app: ancients
    spec:
      containers:
        - name: ancients
          image: galtager1/ancients:latest
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ancients'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_URI
              value: 'mongodb://ancients-mongo-srv:27017/ancients'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ancients-srv
spec:
  type: ClusterIP  # default type for internal expose in the 
  selector:
    app: ancients
  ports: 
    - name: ancients
      protocol: TCP
      port: 3000
      targetPort: 3000