# This is a basic workflow to help you get started with Actions
name: tests
# Controls when the workflow will run
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: cd ancients && npm install && npm run test:ci
